import {
  CREATE_POST_SUCCESS,
  CREATE_POST_FAILED,
  FETCH_POSTS_SUCCESS,
  FETCH_POSTS_FAILED,
  FETCH_POST_SUCCESS,
  FETCH_POST_FAILED,
  EDIT_POST_SUCCESS,
  EDIT_POST_FAILED,
  DELETE_POST_SUCCESS,
  DELETE_POST_FAILED
} from "./types";
import FeedService from "./../services/feedService";
