export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const GOOGLE_SIGNIN_SUCCESS = "GOOGLE_SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";