import {
    FETCH_PROFILE_SUCCESS,
    FETCH_PROFILE_FAILED,
    EDIT_PROFILE_SUCCESS,
    EDIT_PROFILE_FAILED,
    EDIT_PROFILE_PHOTO_SUCCESS,
    EDIT_PROFILE_PHOTO_FAILED,
    FETCH_READINGLIST_SUCCESS,
    FETCH_READINGLIST_FAILED,
    DELETE_FROM_READINGLIST_SUCCESS,
    DELETE_FROM_READINGLIST_FAILED,
  } from "./../actions/types";